"""SQLAlchemy models. Import every model module here so Alembic sees it."""

from app.models.audit import AuditLog
from app.models.base import Base
from app.models.catalog import Customer, Item, ItemComponent, ItemType, VatType
from app.models.documents import (
    DataExport,
    DeliveryStatus,
    Document,
    DocumentDelivery,
    DocumentLine,
    DocumentPayment,
    DocumentRelation,
    DocumentSequence,
    DocumentStatus,
    DocumentType,
    ExportStatus,
    OutboxEvent,
    PaymentMethod,
    RelationType,
    StoredFile,
    VatRate,
)
from app.models.identity import Business, BusinessMember, BusinessType, Invitation, Role, User
from app.models.inventory import MovementKind, StockLevel, StockMovement
from app.models.ita import AllocationRequest, AllocationStatus, ItaConnection
from app.models.notifications import (
    Notification,
    NotificationEvent,
    NotificationPreference,
    PushSubscription,
    UserDevice,
)
from app.models.purchasing import (
    GoodsReceipt,
    GoodsReceiptLine,
    OrderStatus,
    PurchaseOrder,
    PurchaseOrderLine,
    Supplier,
    SupplierInvoice,
)

__all__ = [
    "AllocationRequest",
    "AllocationStatus",
    "AuditLog",
    "Base",
    "Business",
    "BusinessMember",
    "BusinessType",
    "Customer",
    "DataExport",
    "DeliveryStatus",
    "Document",
    "DocumentDelivery",
    "DocumentLine",
    "DocumentPayment",
    "DocumentRelation",
    "DocumentSequence",
    "DocumentStatus",
    "DocumentType",
    "ExportStatus",
    "GoodsReceipt",
    "GoodsReceiptLine",
    "Invitation",
    "ItaConnection",
    "Item",
    "ItemComponent",
    "ItemType",
    "MovementKind",
    "Notification",
    "NotificationEvent",
    "NotificationPreference",
    "OrderStatus",
    "OutboxEvent",
    "PaymentMethod",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "PushSubscription",
    "RelationType",
    "Role",
    "StockLevel",
    "StockMovement",
    "StoredFile",
    "Supplier",
    "SupplierInvoice",
    "User",
    "UserDevice",
    "VatRate",
    "VatType",
]
