"""Document deliveries (emails to customers), tenant-isolated.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 19:27:11.106864
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_deliveries",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("recipients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("variant", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'sent', 'failed')", name=op.f("ck_document_deliveries_status")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_document_deliveries_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_document_deliveries_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_deliveries_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_deliveries")),
    )
    op.create_index(
        op.f("ix_document_deliveries_business_id"),
        "document_deliveries",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_deliveries_document_id"),
        "document_deliveries",
        ["document_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("ALTER TABLE document_deliveries ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE document_deliveries FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY document_deliveries_tenant ON document_deliveries FOR ALL "
        "USING (business_id = app_business_id()) WITH CHECK (business_id = app_business_id())"
    )
    op.execute("GRANT SELECT, INSERT, UPDATE ON document_deliveries TO invoice_app")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS document_deliveries_tenant ON document_deliveries")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_deliveries_document_id"), table_name="document_deliveries")
    op.drop_index(op.f("ix_document_deliveries_business_id"), table_name="document_deliveries")
    op.drop_table("document_deliveries")
    # ### end Alembic commands ###
