"""Catalog and documents: tables, RLS, immutability of issued documents, VAT rates.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 05:49:03.668035
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APP_ROLE = "invoice_app"
TENANT_TABLES = (
    "customers",
    "items",
    "documents",
    "document_lines",
    "document_payments",
    "document_relations",
    "document_sequences",
    "files",
    "outbox_events",
)

# Columns that may still change after a document is issued. Everything else is frozen.
MUTABLE_AFTER_ISSUE = (
    "original_pdf_file_id",
    "original_delivered_at",
    "amount_paid",
    "allocation_number",
    "updated_at",
)

SECURITY_SQL = [
    *[f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY" for t in TENANT_TABLES],
    *[f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY" for t in TENANT_TABLES],
    *[
        f"""
        CREATE POLICY {t}_tenant ON {t} FOR ALL
        USING (business_id = app_business_id()) WITH CHECK (business_id = app_business_id())
        """
        for t in TENANT_TABLES
    ],
    # Issued documents are legal records: no edits (except the columns above) and no deletes.
    f"""
    CREATE FUNCTION documents_guard_issued() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            IF OLD.status = 'issued' THEN
                RAISE EXCEPTION 'issued documents cannot be deleted';
            END IF;
            RETURN OLD;
        END IF;
        IF OLD.status = 'issued' AND (
            to_jsonb(NEW) - ARRAY[{", ".join(f"'{c}'" for c in MUTABLE_AFTER_ISSUE)}]
        ) IS DISTINCT FROM (
            to_jsonb(OLD) - ARRAY[{", ".join(f"'{c}'" for c in MUTABLE_AFTER_ISSUE)}]
        ) THEN
            RAISE EXCEPTION 'issued documents cannot be changed';
        END IF;
        RETURN NEW;
    END $$
    """,
    """
    CREATE TRIGGER documents_guard_issued BEFORE UPDATE OR DELETE ON documents
    FOR EACH ROW EXECUTE FUNCTION documents_guard_issued()
    """,
    # Lines and payments of an issued document are frozen too.
    """
    CREATE FUNCTION document_children_guard_issued() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
        doc_id uuid := CASE WHEN TG_OP = 'DELETE' THEN OLD.document_id ELSE NEW.document_id END;
    BEGIN
        IF EXISTS (SELECT 1 FROM documents WHERE id = doc_id AND status = 'issued') THEN
            RAISE EXCEPTION 'lines and payments of issued documents cannot be changed';
        END IF;
        RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
    END $$
    """,
    *[
        f"""
        CREATE TRIGGER {t}_guard_issued BEFORE INSERT OR UPDATE OR DELETE ON {t}
        FOR EACH ROW EXECUTE FUNCTION document_children_guard_issued()
        """
        for t in ("document_lines", "document_payments")
    ],
    f"GRANT SELECT, INSERT, UPDATE, DELETE ON customers, items, documents, document_lines, "
    f"document_payments, document_relations TO {APP_ROLE}",
    f"GRANT SELECT, INSERT, UPDATE ON document_sequences TO {APP_ROLE}",
    f"GRANT SELECT, INSERT ON files TO {APP_ROLE}",
    f"GRANT SELECT, INSERT, UPDATE ON outbox_events TO {APP_ROLE}",
    f"GRANT SELECT ON vat_rates TO {APP_ROLE}",
    # Israeli VAT history (standard rate). Further changes are added by new migrations.
    """
    INSERT INTO vat_rates (id, rate, effective_from) VALUES
        (gen_random_uuid(), 0.1700, DATE '2015-10-01'),
        (gen_random_uuid(), 0.1800, DATE '2025-01-01')
    """,
]

DOWNGRADE_SECURITY_SQL = [
    "DROP TRIGGER IF EXISTS document_lines_guard_issued ON document_lines",
    "DROP TRIGGER IF EXISTS document_payments_guard_issued ON document_payments",
    "DROP FUNCTION IF EXISTS document_children_guard_issued()",
    "DROP TRIGGER IF EXISTS documents_guard_issued ON documents",
    "DROP FUNCTION IF EXISTS documents_guard_issued()",
    *[f"DROP POLICY IF EXISTS {t}_tenant ON {t}" for t in TENANT_TABLES],
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vat_rates",
        sa.Column("rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vat_rates")),
        sa.UniqueConstraint("effective_from", name=op.f("uq_vat_rates_effective_from")),
    )
    op.create_table(
        "customers",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tax_id", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("address_street", sa.String(length=200), nullable=False),
        sa.Column("address_city", sa.String(length=100), nullable=False),
        sa.Column("address_zip", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_customers_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(op.f("ix_customers_business_id"), "customers", ["business_id"], unique=False)
    op.create_index(
        "ix_customers_business_name", "customers", ["business_id", "name"], unique=False
    )
    op.create_table(
        "document_sequences",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("next_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_document_sequences_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("business_id", "document_type", name=op.f("pk_document_sequences")),
    )
    op.create_table(
        "files",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_files_business_id_businesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_files_storage_key")),
    )
    op.create_index(op.f("ix_files_business_id"), "files", ["business_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("item_type", sa.String(length=10), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=20), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vat_type", sa.String(length=10), nullable=False),
        sa.Column("track_inventory", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("item_type IN ('product', 'service')", name=op.f("ck_items_item_type")),
        sa.CheckConstraint(
            "vat_type IN ('standard', 'exempt', 'zero')", name=op.f("ck_items_vat_type")
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_items_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_items_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    )
    op.create_index(op.f("ix_items_business_id"), "items", ["business_id"], unique=False)
    op.create_index("ix_items_business_name", "items", ["business_id", "name"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_outbox_events_business_id_businesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_business_id"), "outbox_events", ["business_id"], unique=False
    )
    op.create_index(
        "ix_outbox_events_pending", "outbox_events", ["status", "available_at"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "customer",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("business_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("prices_include_vat", sa.Boolean(), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("allocation_number", sa.String(length=20), nullable=True),
        sa.Column("original_pdf_file_id", sa.Uuid(), nullable=True),
        sa.Column("original_delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("issued_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'draft' AND number IS NULL) OR (status = 'issued' AND number IS NOT NULL)",
            name=op.f("ck_documents_number_iff_issued"),
        ),
        sa.CheckConstraint("status IN ('draft', 'issued')", name=op.f("ck_documents_status")),
        sa.CheckConstraint(
            "type IN ('quote', 'proforma_invoice', 'tax_invoice', 'receipt', 'tax_invoice_receipt', 'credit_note')",
            name=op.f("ck_documents_type"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_documents_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], name=op.f("fk_documents_created_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_documents_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"], ["users.id"], name=op.f("fk_documents_issued_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["original_pdf_file_id"],
            ["files.id"],
            name=op.f("fk_documents_original_pdf_file_id_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("business_id", "type", "number", name=op.f("uq_documents_business_id")),
    )
    op.create_index(op.f("ix_documents_business_id"), "documents", ["business_id"], unique=False)
    op.create_index(
        "ix_documents_business_issue_date", "documents", ["business_id", "issue_date"], unique=False
    )
    op.create_index(
        "ix_documents_business_type_status",
        "documents",
        ["business_id", "type", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_customer_id"), "documents", ["customer_id"], unique=False)
    op.create_table(
        "document_lines",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=20), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("vat_type", sa.String(length=10), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "vat_type IN ('standard', 'exempt', 'zero')", name=op.f("ck_document_lines_vat_type")
        ),
        sa.CheckConstraint(
            "discount_percent >= 0 AND discount_percent <= 100",
            name=op.f("ck_document_lines_discount_range"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_document_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_document_lines_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_document_lines_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_lines_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_document_lines_item_id_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_lines")),
    )
    op.create_index(
        op.f("ix_document_lines_business_id"), "document_lines", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_lines_document_id"), "document_lines", ["document_id"], unique=False
    )
    op.create_table(
        "document_payments",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "method IN ('cash', 'check', 'credit_card', 'bank_transfer', 'digital_wallet', 'other')",
            name=op.f("ck_document_payments_method"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_document_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_document_payments_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_payments_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_payments")),
    )
    op.create_index(
        op.f("ix_document_payments_business_id"), "document_payments", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_payments_document_id"), "document_payments", ["document_id"], unique=False
    )
    op.create_table(
        "document_relations",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("from_document_id", sa.Uuid(), nullable=False),
        sa.Column("to_document_id", sa.Uuid(), nullable=False),
        sa.Column("relation", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "relation IN ('converted_from', 'credits', 'pays')",
            name=op.f("ck_document_relations_relation"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_document_relations_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["from_document_id"],
            ["documents.id"],
            name=op.f("fk_document_relations_from_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_document_id"],
            ["documents.id"],
            name=op.f("fk_document_relations_to_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_relations")),
        sa.UniqueConstraint(
            "from_document_id",
            "to_document_id",
            "relation",
            name=op.f("uq_document_relations_from_document_id"),
        ),
    )
    op.create_index(
        op.f("ix_document_relations_business_id"),
        "document_relations",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_relations_from_document_id"),
        "document_relations",
        ["from_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_relations_to_document_id"),
        "document_relations",
        ["to_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    for statement in SECURITY_SQL:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE_SECURITY_SQL:
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_relations_to_document_id"), table_name="document_relations")
    op.drop_index(op.f("ix_document_relations_from_document_id"), table_name="document_relations")
    op.drop_index(op.f("ix_document_relations_business_id"), table_name="document_relations")
    op.drop_table("document_relations")
    op.drop_index(op.f("ix_document_payments_document_id"), table_name="document_payments")
    op.drop_index(op.f("ix_document_payments_business_id"), table_name="document_payments")
    op.drop_table("document_payments")
    op.drop_index(op.f("ix_document_lines_document_id"), table_name="document_lines")
    op.drop_index(op.f("ix_document_lines_business_id"), table_name="document_lines")
    op.drop_table("document_lines")
    op.drop_index(op.f("ix_documents_customer_id"), table_name="documents")
    op.drop_index("ix_documents_business_type_status", table_name="documents")
    op.drop_index("ix_documents_business_issue_date", table_name="documents")
    op.drop_index(op.f("ix_documents_business_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_outbox_events_pending", table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_business_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_items_business_name", table_name="items")
    op.drop_index(op.f("ix_items_business_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_files_business_id"), table_name="files")
    op.drop_table("files")
    op.drop_table("document_sequences")
    op.drop_index("ix_customers_business_name", table_name="customers")
    op.drop_index(op.f("ix_customers_business_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_table("vat_rates")
    # ### end Alembic commands ###
