"""Business logo; receipts applied to invoices; paid/credited amounts on invoices.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 18:21:40.256883
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PREVIOUS_MUTABLE = (
    "original_pdf_file_id",
    "original_delivered_at",
    "amount_paid",
    "allocation_number",
    "updated_at",
)
MUTABLE_AFTER_ISSUE = (*PREVIOUS_MUTABLE, "amount_credited")


def guard_function(mutable: tuple[str, ...]) -> str:
    """Issued documents stay frozen except for the listed bookkeeping columns."""
    columns = ", ".join(f"'{c}'" for c in mutable)
    return f"""
    CREATE OR REPLACE FUNCTION documents_guard_issued() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            IF OLD.status = 'issued' THEN
                RAISE EXCEPTION 'issued documents cannot be deleted';
            END IF;
            RETURN OLD;
        END IF;
        IF OLD.status = 'issued' AND (to_jsonb(NEW) - ARRAY[{columns}])
            IS DISTINCT FROM (to_jsonb(OLD) - ARRAY[{columns}]) THEN
            RAISE EXCEPTION 'issued documents cannot be changed';
        END IF;
        RETURN NEW;
    END $$
    """


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("businesses", sa.Column("logo_file_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_businesses_logo_file_id_files",
        "businesses",
        "files",
        ["logo_file_id"],
        ["id"],
        use_alter=True,
    )
    op.add_column(
        "document_relations", sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "documents",
        sa.Column(
            "amount_credited", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###

    op.execute(guard_function(MUTABLE_AFTER_ISSUE))
    op.execute(
        "ALTER TABLE document_relations ADD CONSTRAINT ck_document_relations_pays_amount "
        "CHECK (relation <> 'pays' OR amount > 0)"
    )
    # Backfill: invoice-receipts are paid in full; credit notes reduce their invoice's balance.
    op.execute(
        "UPDATE documents SET amount_paid = total "
        "WHERE type = 'tax_invoice_receipt' AND status = 'issued'"
    )
    op.execute("""
        UPDATE documents d SET amount_credited = c.credited
        FROM (
            SELECT r.to_document_id AS invoice_id, sum(cn.total) AS credited
            FROM document_relations r JOIN documents cn ON cn.id = r.from_document_id
            WHERE r.relation = 'credits' AND cn.status = 'issued'
            GROUP BY r.to_document_id
        ) c
        WHERE d.id = c.invoice_id
    """)


def downgrade() -> None:
    op.execute("ALTER TABLE document_relations DROP CONSTRAINT ck_document_relations_pays_amount")
    op.execute(guard_function(PREVIOUS_MUTABLE))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "amount_credited")
    op.drop_column("document_relations", "amount")
    op.drop_constraint("fk_businesses_logo_file_id_files", "businesses", type_="foreignkey")
    op.drop_column("businesses", "logo_file_id")
    # ### end Alembic commands ###
