"""Purchasing: suppliers, purchase orders, goods receipts, supplier invoices

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-09 12:02:07.577151
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "invoice_app"
TABLES = (
    "suppliers",
    "purchase_orders",
    "purchase_order_lines",
    "goods_receipts",
    "goods_receipt_lines",
    "supplier_invoices",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tax_id", sa.String(length=20), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("address_street", sa.String(length=200), nullable=False),
        sa.Column("address_city", sa.String(length=100), nullable=False),
        sa.Column("address_zip", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_suppliers_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
    )
    op.create_index(op.f("ix_suppliers_business_id"), "suppliers", ["business_id"], unique=False)
    op.create_index(
        "ix_suppliers_business_name", "suppliers", ["business_id", "name"], unique=False
    )
    op.create_table(
        "purchase_orders",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'partial', 'received', 'cancelled')",
            name=op.f("ck_purchase_orders_status"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_purchase_orders_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_purchase_orders_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_purchase_orders_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint("business_id", "number", name="uq_purchase_orders_number"),
    )
    op.create_index(
        op.f("ix_purchase_orders_business_id"), "purchase_orders", ["business_id"], unique=False
    )
    op.create_table(
        "goods_receipts",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("supplier_reference", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_goods_receipts_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_goods_receipts_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_goods_receipts_purchase_order_id_purchase_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_goods_receipts_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipts")),
        sa.UniqueConstraint("business_id", "number", name="uq_goods_receipts_number"),
    )
    op.create_index(
        op.f("ix_goods_receipts_business_id"), "goods_receipts", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipts_purchase_order_id"),
        "goods_receipts",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("received_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_order_lines_quantity_positive")),
        sa.CheckConstraint(
            "received_quantity >= 0", name=op.f("ck_purchase_order_lines_received_non_negative")
        ),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_purchase_order_lines_unit_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_purchase_order_lines_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_purchase_order_lines_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_order_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_business_id"),
        "purchase_order_lines",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_lines_order_id"), "purchase_order_lines", ["order_id"], unique=False
    )
    op.create_table(
        "supplier_invoices",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("net_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "net_amount >= 0 AND vat_amount >= 0",
            name=op.f("ck_supplier_invoices_amounts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_supplier_invoices_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_supplier_invoices_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_supplier_invoices_purchase_order_id_purchase_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_invoices_supplier_id_suppliers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_invoices")),
        sa.UniqueConstraint(
            "business_id", "supplier_id", "invoice_number", name="uq_supplier_invoices_number"
        ),
    )
    op.create_index(
        op.f("ix_supplier_invoices_business_id"), "supplier_invoices", ["business_id"], unique=False
    )
    op.create_table(
        "goods_receipt_lines",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("order_line_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_goods_receipt_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_goods_receipt_lines_unit_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_goods_receipt_lines_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_goods_receipt_lines_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_goods_receipt_lines_order_line_id_purchase_order_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["goods_receipts.id"],
            name=op.f("fk_goods_receipt_lines_receipt_id_goods_receipts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_lines")),
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_business_id"),
        "goods_receipt_lines",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_receipt_id"),
        "goods_receipt_lines",
        ["receipt_id"],
        unique=False,
    )
    op.add_column("stock_movements", sa.Column("goods_receipt_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_stock_movements_goods_receipt_id_goods_receipts"),
        "stock_movements",
        "goods_receipts",
        ["goods_receipt_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant ON {table} FOR ALL "
            "USING (business_id = app_business_id()) WITH CHECK (business_id = app_business_id())"
        )
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON suppliers, purchase_orders TO {APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON purchase_order_lines TO {APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON supplier_invoices TO {APP_ROLE}")
    # Goods receipts are a record of what arrived: never changed or deleted.
    op.execute(f"GRANT SELECT, INSERT ON goods_receipts, goods_receipt_lines TO {APP_ROLE}")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_stock_movements_goods_receipt_id_goods_receipts"),
        "stock_movements",
        type_="foreignkey",
    )
    op.drop_column("stock_movements", "goods_receipt_id")
    op.drop_index(op.f("ix_goods_receipt_lines_receipt_id"), table_name="goods_receipt_lines")
    op.drop_index(op.f("ix_goods_receipt_lines_business_id"), table_name="goods_receipt_lines")
    op.drop_table("goods_receipt_lines")
    op.drop_index(op.f("ix_supplier_invoices_business_id"), table_name="supplier_invoices")
    op.drop_table("supplier_invoices")
    op.drop_index(op.f("ix_purchase_order_lines_order_id"), table_name="purchase_order_lines")
    op.drop_index(op.f("ix_purchase_order_lines_business_id"), table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_goods_receipts_purchase_order_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_business_id"), table_name="goods_receipts")
    op.drop_table("goods_receipts")
    op.drop_index(op.f("ix_purchase_orders_business_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index("ix_suppliers_business_name", table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_business_id"), table_name="suppliers")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
