"""Tax authority allocation numbers: connections and requests

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-09 13:31:25.466867
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "invoice_app"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ita_connections",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=20), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_ita_connections_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["connected_by_user_id"],
            ["users.id"],
            name=op.f("fk_ita_connections_connected_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("business_id", name=op.f("pk_ita_connections")),
    )
    op.create_table(
        "allocation_requests",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("allocation_number", sa.String(length=20), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("request_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('approved', 'pending', 'rejected')",
            name=op.f("ck_allocation_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_allocation_requests_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_allocation_requests_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_requests")),
    )
    op.create_index(
        op.f("ix_allocation_requests_business_id"),
        "allocation_requests",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        "ix_allocation_requests_document",
        "allocation_requests",
        ["document_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in ("ita_connections", "allocation_requests"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant ON {table} FOR ALL "
            "USING (business_id = app_business_id()) WITH CHECK (business_id = app_business_id())"
        )
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ita_connections TO {APP_ROLE}")
    # The request log is kept: no deletes.
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON allocation_requests TO {APP_ROLE}")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_allocation_requests_document", table_name="allocation_requests")
    op.drop_index(op.f("ix_allocation_requests_business_id"), table_name="allocation_requests")
    op.drop_table("allocation_requests")
    op.drop_table("ita_connections")
    # ### end Alembic commands ###
