"""Known devices (new sign-in alerts), account-level notifications, daily summaries.

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-07 10:51:13.179744
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "invoice_app"

SECURITY = (
    "ALTER TABLE user_devices ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE user_devices FORCE ROW LEVEL SECURITY",
    """
    CREATE POLICY user_devices_own ON user_devices FOR ALL
    USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id())
    """,
    f"GRANT SELECT, INSERT, UPDATE, DELETE ON user_devices TO {APP_ROLE}",
    # Account-level notifications (no business) are written by the user's own session.
    "DROP POLICY notifications_insert ON notifications",
    """
    CREATE POLICY notifications_insert ON notifications FOR INSERT WITH CHECK (
        (business_id IS NULL AND user_id = app_user_id())
        OR (
            business_id = app_business_id()
            AND EXISTS (SELECT 1 FROM business_members m
                        WHERE m.business_id = notifications.business_id
                          AND m.user_id = notifications.user_id)
        )
    )
    """,
    # One summary event per business that has issued documents, once per day.
    """
    CREATE FUNCTION enqueue_daily_summaries(summary_day date) RETURNS integer
    LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp AS $$
        WITH due AS (
            INSERT INTO outbox_events
                (id, business_id, event_type, payload, status, attempts, available_at, created_at)
            SELECT gen_random_uuid(), b.business_id, 'business.daily_summary',
                   jsonb_build_object('day', summary_day), 'pending', 0, now(), now()
            FROM (SELECT DISTINCT business_id FROM documents WHERE status = 'issued') b
            WHERE NOT EXISTS (
                SELECT 1 FROM outbox_events e
                WHERE e.business_id = b.business_id
                  AND e.event_type = 'business.daily_summary'
                  AND e.payload ->> 'day' = summary_day::text
            )
            RETURNING 1
        )
        SELECT count(*)::integer FROM due
    $$
    """,
    "REVOKE ALL ON FUNCTION enqueue_daily_summaries(date) FROM PUBLIC",
    f"GRANT EXECUTE ON FUNCTION enqueue_daily_summaries(date) TO {APP_ROLE}",
)

UNDO_SECURITY = (
    "DROP FUNCTION enqueue_daily_summaries(date)",
    "DELETE FROM notifications WHERE business_id IS NULL",
    "DROP POLICY notifications_insert ON notifications",
    """
    CREATE POLICY notifications_insert ON notifications FOR INSERT WITH CHECK (
        business_id = app_business_id()
        AND EXISTS (SELECT 1 FROM business_members m
                    WHERE m.business_id = notifications.business_id
                      AND m.user_id = notifications.user_id)
    )
    """,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_devices",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("last_ip", sa.String(length=64), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_devices_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_devices")),
        sa.UniqueConstraint("user_id", "device_hash", name="uq_user_devices_device"),
    )
    op.create_index(op.f("ix_user_devices_user_id"), "user_devices", ["user_id"], unique=False)
    op.alter_column("notifications", "business_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
    for statement in SECURITY:
        op.execute(statement)


def downgrade() -> None:
    for statement in UNDO_SECURITY:
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notifications", "business_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("ix_user_devices_user_id"), table_name="user_devices")
    op.drop_table("user_devices")
    # ### end Alembic commands ###
