"""Inventory: stock levels, movements, sales kits

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-09 10:13:50.907311
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "invoice_app"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_components",
        sa.Column("kit_item_id", sa.Uuid(), nullable=False),
        sa.Column("component_item_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_item_components_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_item_components_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["component_item_id"],
            ["items.id"],
            name=op.f("fk_item_components_component_item_id_items"),
        ),
        sa.ForeignKeyConstraint(
            ["kit_item_id"],
            ["items.id"],
            name=op.f("fk_item_components_kit_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "kit_item_id", "component_item_id", name=op.f("pk_item_components")
        ),
    )
    op.create_index(
        op.f("ix_item_components_business_id"), "item_components", ["business_id"], unique=False
    )
    op.create_table(
        "stock_levels",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_stock_levels_business_id_businesses")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_stock_levels_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("business_id", "item_id", name=op.f("pk_stock_levels")),
    )
    op.create_table(
        "stock_movements",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("kit_item_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_stock_movements_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_stock_movements_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_stock_movements_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_stock_movements_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["kit_item_id"], ["items.id"], name=op.f("fk_stock_movements_kit_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        op.f("ix_stock_movements_business_id"), "stock_movements", ["business_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_item",
        "stock_movements",
        ["business_id", "item_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "documents",
        sa.Column("returns_stock", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column("items", sa.Column("min_stock", sa.Numeric(precision=14, scale=3), nullable=True))
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_items_item_type"), "items", type_="check")
    op.create_check_constraint("item_type", "items", "item_type IN ('product', 'service', 'kit')")
    for table in ("item_components", "stock_levels", "stock_movements"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant ON {table} FOR ALL "
            "USING (business_id = app_business_id()) WITH CHECK (business_id = app_business_id())"
        )
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON item_components TO {APP_ROLE}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON stock_levels TO {APP_ROLE}")
    # The ledger is append-only: no updates, no deletes.
    op.execute(f"GRANT SELECT, INSERT ON stock_movements TO {APP_ROLE}")


def downgrade() -> None:
    op.execute("DELETE FROM items WHERE item_type = 'kit'")
    op.drop_constraint(op.f("ck_items_item_type"), "items", type_="check")
    op.create_check_constraint("item_type", "items", "item_type IN ('product', 'service')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "min_stock")
    op.drop_column("documents", "returns_stock")
    op.drop_index("ix_stock_movements_item", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_business_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_table("stock_levels")
    op.drop_index(op.f("ix_item_components_business_id"), table_name="item_components")
    op.drop_table("item_components")
    # ### end Alembic commands ###
